#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py createsuperuser --no-input
uvicorn config.asgi:application --host 0.0.0.0 --port {{cookiecutter.d4service_spot_port}} --reload
