@startuml
!include include/d4_inc_scope.puml

package co as "Company Oceanic Airlines" {
    $d4scope(co, scp1, "Booking system (Scope 1)", $show_ds5=true, $show_rproxy=false, $show_cache=true, $show_ui=true, $show_ui_user=true, $show_adpt=true)
}

@enduml