@startuml
!include include/d4_inc_base.puml

!include include/context_framework.puml
!include include/context_development.puml
!include include/context_operation.puml

ctxframe_d4 --> ctxdev_toolset1
ctxdev_package1 ~~> ctxops_service_conv1

$d4legend()
@enduml
