@startuml
'!theme spacelab
'!include config.skinparam
'skinparam monochrome true

skinparam LegendFontSize 8

!procedure $d4legend()
    legend right
      %filename() / %date("yyyy-MM-dd'T'HH:mmZ") / [[https://plantuml.com PlantUML (%version())]]
    endlegend
!endprocedure

!if (%false())
    $d4legend()
!endif

@enduml